import type { RiskSignal, RiskMitigator } from "../types";

export const RISK_WEIGHTS: Record<RiskSignal, number> = {
  FIRST_TIME_PAYEE: 12,
  HIGH_AMOUNT_RELATIVE_TO_BASELINE: 10,
  SHORT_LATENCY_AFTER_MESSAGE: 10,
  MISTAKEN_TRANSFER_CLAIM: 8,
  URGENCY_PRESSURE: 10,
  REFUND_LANGUAGE: 5,
  PAYEE_SOURCED_FROM_MESSAGE: 7,
  COUNTERPARTY_MISMATCH: 20,
  NEW_PAYEE: 10,
  INBOUND_CREDIT_UNVERIFIED: 15,
  AMOUNT_ECHO: 5,
  NO_MATCHING_INCOMING_PAYMENT: 20,
};

export const MITIGATOR_WEIGHTS: Record<RiskMitigator, number> = {
  KNOWN_CONTACT: -8,
  ESTABLISHED_PAYEE: -12,
  VERIFIED_INCOMING_PAYMENT: -20,
  RECURRING_PAYMENT_PATTERN: -10,
  VERIFIED_MERCHANT_CONTEXT: -10,
};
